### PR TITLE
Fix duplicate @providesModule conflict / Unable to resolve module AccessibilityInfo

### PR DESCRIPTION
**Pull request by peacechen**
A library should not have react or react-native in its dependencies.
Move them to devDependencies.

See #2

### CODE REVIEW

**Comment by bamaarintoko** [comment]
i still have this issue

**Comment by peacechen** [comment]
The fix was merged but a new version hasn't been published to npm.  You'll need to point directly to this repo in your package.json.

**Comment by bamaarintoko** [comment]
how to point directly to this repo?

**Comment by peacechen** [comment]
```
    "react-native-swipe-hidden-header": "https://github.com/fengliu222/react-native-swipe-hidden-header",
```

**Pull request merged**
